/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding/role'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AppVenueRouteRouteImport } from './routes/_app/venue/route'
import { Route as AppHostRouteRouteImport } from './routes/_app/host/route'
import { Route as AppVenueProfileRouteImport } from './routes/_app/venue/profile'
import { Route as AppVenueVenueIdRouteImport } from './routes/_app/venue/$venueId'
import { Route as AppHostBriefsIndexRouteImport } from './routes/_app/host/briefs/index'
import { Route as AppHostBriefsNewRouteImport } from './routes/_app/host/briefs/new'
import { Route as AppHostBriefsBriefIdRouteRouteImport } from './routes/_app/host/briefs/$briefId/route'
import { Route as AppHostBriefsBriefIdIndexRouteImport } from './routes/_app/host/briefs/$briefId/index'
import { Route as AppHostBriefsBriefIdEditRouteImport } from './routes/_app/host/briefs/$briefId/edit'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/onboarding/role',
  path: '/onboarding/role',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppVenueRouteRoute = AppVenueRouteRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHostRouteRoute = AppHostRouteRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVenueProfileRoute = AppVenueProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppVenueRouteRoute,
} as any)
const AppVenueVenueIdRoute = AppVenueVenueIdRouteImport.update({
  id: '/$venueId',
  path: '/$venueId',
  getParentRoute: () => AppVenueRouteRoute,
} as any)
const AppHostBriefsIndexRoute = AppHostBriefsIndexRouteImport.update({
  id: '/briefs/',
  path: '/briefs/',
  getParentRoute: () => AppHostRouteRoute,
} as any)
const AppHostBriefsNewRoute = AppHostBriefsNewRouteImport.update({
  id: '/briefs/new',
  path: '/briefs/new',
  getParentRoute: () => AppHostRouteRoute,
} as any)
const AppHostBriefsBriefIdRouteRoute =
  AppHostBriefsBriefIdRouteRouteImport.update({
    id: '/briefs/$briefId',
    path: '/briefs/$briefId',
    getParentRoute: () => AppHostRouteRoute,
  } as any)
const AppHostBriefsBriefIdIndexRoute =
  AppHostBriefsBriefIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppHostBriefsBriefIdRouteRoute,
  } as any)
const AppHostBriefsBriefIdEditRoute =
  AppHostBriefsBriefIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppHostBriefsBriefIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/host': typeof AppHostRouteRouteWithChildren
  '/venue': typeof AppVenueRouteRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/venue/$venueId': typeof AppVenueVenueIdRoute
  '/venue/profile': typeof AppVenueProfileRoute
  '/host/briefs/$briefId': typeof AppHostBriefsBriefIdRouteRouteWithChildren
  '/host/briefs/new': typeof AppHostBriefsNewRoute
  '/host/briefs/': typeof AppHostBriefsIndexRoute
  '/host/briefs/$briefId/edit': typeof AppHostBriefsBriefIdEditRoute
  '/host/briefs/$briefId/': typeof AppHostBriefsBriefIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/host': typeof AppHostRouteRouteWithChildren
  '/venue': typeof AppVenueRouteRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/venue/$venueId': typeof AppVenueVenueIdRoute
  '/venue/profile': typeof AppVenueProfileRoute
  '/host/briefs/new': typeof AppHostBriefsNewRoute
  '/host/briefs': typeof AppHostBriefsIndexRoute
  '/host/briefs/$briefId/edit': typeof AppHostBriefsBriefIdEditRoute
  '/host/briefs/$briefId': typeof AppHostBriefsBriefIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_app/host': typeof AppHostRouteRouteWithChildren
  '/_app/venue': typeof AppVenueRouteRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/_app/venue/$venueId': typeof AppVenueVenueIdRoute
  '/_app/venue/profile': typeof AppVenueProfileRoute
  '/_app/host/briefs/$briefId': typeof AppHostBriefsBriefIdRouteRouteWithChildren
  '/_app/host/briefs/new': typeof AppHostBriefsNewRoute
  '/_app/host/briefs/': typeof AppHostBriefsIndexRoute
  '/_app/host/briefs/$briefId/edit': typeof AppHostBriefsBriefIdEditRoute
  '/_app/host/briefs/$briefId/': typeof AppHostBriefsBriefIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/host'
    | '/venue'
    | '/login'
    | '/register'
    | '/onboarding/role'
    | '/venue/$venueId'
    | '/venue/profile'
    | '/host/briefs/$briefId'
    | '/host/briefs/new'
    | '/host/briefs/'
    | '/host/briefs/$briefId/edit'
    | '/host/briefs/$briefId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/host'
    | '/venue'
    | '/login'
    | '/register'
    | '/onboarding/role'
    | '/venue/$venueId'
    | '/venue/profile'
    | '/host/briefs/new'
    | '/host/briefs'
    | '/host/briefs/$briefId/edit'
    | '/host/briefs/$briefId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_public'
    | '/_app/host'
    | '/_app/venue'
    | '/_public/login'
    | '/_public/register'
    | '/onboarding/role'
    | '/_app/venue/$venueId'
    | '/_app/venue/profile'
    | '/_app/host/briefs/$briefId'
    | '/_app/host/briefs/new'
    | '/_app/host/briefs/'
    | '/_app/host/briefs/$briefId/edit'
    | '/_app/host/briefs/$briefId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  OnboardingRoleRoute: typeof OnboardingRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/role': {
      id: '/onboarding/role'
      path: '/onboarding/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_app/venue': {
      id: '/_app/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof AppVenueRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/host': {
      id: '/_app/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof AppHostRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/venue/profile': {
      id: '/_app/venue/profile'
      path: '/profile'
      fullPath: '/venue/profile'
      preLoaderRoute: typeof AppVenueProfileRouteImport
      parentRoute: typeof AppVenueRouteRoute
    }
    '/_app/venue/$venueId': {
      id: '/_app/venue/$venueId'
      path: '/$venueId'
      fullPath: '/venue/$venueId'
      preLoaderRoute: typeof AppVenueVenueIdRouteImport
      parentRoute: typeof AppVenueRouteRoute
    }
    '/_app/host/briefs/': {
      id: '/_app/host/briefs/'
      path: '/briefs'
      fullPath: '/host/briefs/'
      preLoaderRoute: typeof AppHostBriefsIndexRouteImport
      parentRoute: typeof AppHostRouteRoute
    }
    '/_app/host/briefs/new': {
      id: '/_app/host/briefs/new'
      path: '/briefs/new'
      fullPath: '/host/briefs/new'
      preLoaderRoute: typeof AppHostBriefsNewRouteImport
      parentRoute: typeof AppHostRouteRoute
    }
    '/_app/host/briefs/$briefId': {
      id: '/_app/host/briefs/$briefId'
      path: '/briefs/$briefId'
      fullPath: '/host/briefs/$briefId'
      preLoaderRoute: typeof AppHostBriefsBriefIdRouteRouteImport
      parentRoute: typeof AppHostRouteRoute
    }
    '/_app/host/briefs/$briefId/': {
      id: '/_app/host/briefs/$briefId/'
      path: '/'
      fullPath: '/host/briefs/$briefId/'
      preLoaderRoute: typeof AppHostBriefsBriefIdIndexRouteImport
      parentRoute: typeof AppHostBriefsBriefIdRouteRoute
    }
    '/_app/host/briefs/$briefId/edit': {
      id: '/_app/host/briefs/$briefId/edit'
      path: '/edit'
      fullPath: '/host/briefs/$briefId/edit'
      preLoaderRoute: typeof AppHostBriefsBriefIdEditRouteImport
      parentRoute: typeof AppHostBriefsBriefIdRouteRoute
    }
  }
}

interface AppHostBriefsBriefIdRouteRouteChildren {
  AppHostBriefsBriefIdEditRoute: typeof AppHostBriefsBriefIdEditRoute
  AppHostBriefsBriefIdIndexRoute: typeof AppHostBriefsBriefIdIndexRoute
}

const AppHostBriefsBriefIdRouteRouteChildren: AppHostBriefsBriefIdRouteRouteChildren =
  {
    AppHostBriefsBriefIdEditRoute: AppHostBriefsBriefIdEditRoute,
    AppHostBriefsBriefIdIndexRoute: AppHostBriefsBriefIdIndexRoute,
  }

const AppHostBriefsBriefIdRouteRouteWithChildren =
  AppHostBriefsBriefIdRouteRoute._addFileChildren(
    AppHostBriefsBriefIdRouteRouteChildren,
  )

interface AppHostRouteRouteChildren {
  AppHostBriefsBriefIdRouteRoute: typeof AppHostBriefsBriefIdRouteRouteWithChildren
  AppHostBriefsNewRoute: typeof AppHostBriefsNewRoute
  AppHostBriefsIndexRoute: typeof AppHostBriefsIndexRoute
}

const AppHostRouteRouteChildren: AppHostRouteRouteChildren = {
  AppHostBriefsBriefIdRouteRoute: AppHostBriefsBriefIdRouteRouteWithChildren,
  AppHostBriefsNewRoute: AppHostBriefsNewRoute,
  AppHostBriefsIndexRoute: AppHostBriefsIndexRoute,
}

const AppHostRouteRouteWithChildren = AppHostRouteRoute._addFileChildren(
  AppHostRouteRouteChildren,
)

interface AppVenueRouteRouteChildren {
  AppVenueVenueIdRoute: typeof AppVenueVenueIdRoute
  AppVenueProfileRoute: typeof AppVenueProfileRoute
}

const AppVenueRouteRouteChildren: AppVenueRouteRouteChildren = {
  AppVenueVenueIdRoute: AppVenueVenueIdRoute,
  AppVenueProfileRoute: AppVenueProfileRoute,
}

const AppVenueRouteRouteWithChildren = AppVenueRouteRoute._addFileChildren(
  AppVenueRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppHostRouteRoute: typeof AppHostRouteRouteWithChildren
  AppVenueRouteRoute: typeof AppVenueRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppHostRouteRoute: AppHostRouteRouteWithChildren,
  AppVenueRouteRoute: AppVenueRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  OnboardingRoleRoute: OnboardingRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
